### ISSUE TITLE
Can you add a tutorial of how to use these files?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [aaalgo/box#1]
I would like thank you for sharing the project. 

Could you add a short tutorial (readme) of how to use these codes in sequence, especially how to load images for training, or if users are allowed to pre-trained weights for fine-tuning? 

Thank you!

**Comment by aaalgo** [comment]
I'm still working on these.  Please email me.

**Comment by aaalgo** [comment]
My codebase is not well-documented.  It's still under constant changes.  Please contact me by email to discuss.
